### ISSUE TITLE
policy_providers configuration seems to be broken in config.devel.yaml

### ISSUE THREAD

**Issue by juamedgod** [chainloop-dev/chainloop#1365]
It seems there is a problem with the deprecation of the `host` field. When running `make -C app/controlplane run` I get:

```
DEBUG msg=config loaded: config.devel.yaml format: yaml
panic: validation error:
	 - policy_providers[0].host: value must be a valid URI [string.uri]

goroutine 1 [running]:
main.main()
	chainloop/chainloop/app/controlplane/cmd/main.go:104 +0x5fc
exit status 2
make: *** [run] Error 1
```

After filling up `host` I get a new error:

```
INFO msg=watcher's ctx cancel : context canceled
panic: wrong configuration for policy provider. Either URL or host (deprecated) must be provided, but not both

goroutine 1 [running]:
main.main()
	chainloop/chainloop/app/controlplane/cmd/main.go:142 +0x59c
exit status 2
make: *** [run] Error 1
```

The only way to make it work is to remove url and use the deprecated host setting, which only throws a warning but makes it work:

```
2024-10-08T11:22:08.726+0200	WARN	{"msg": "the policy provider 'chainloop' is using a deprecated 'host' configuration with value 'http://localhost:8002/v1'. Please use 'url' instead. Configuring 'url' with value 'http://localhost:8002/v1'"}
github.com/go-kratos/kratos/contrib/log/zap/v2.(*Logger).Log
	go/pkg/mod/github.com/go-kratos/kratos/contrib/log/zap/v2@v2.0.0-20230823024326-a09f4d8ebba9/zap.go:39
github.com/go-kratos/kratos/v2/log.(*logger).Log
	go/pkg/mod/github.com/go-kratos/kratos/v2@v2.7.0/log/log.go:30
github.com/go-kratos/kratos/v2/log.(*Filter).Log
	go/pkg/mod/github.com/go-kratos/kratos/v2@v2.7.0/log/filter.go:99
github.com/go-kratos/kratos/v2/log.(*Helper).Warnf
	go/pkg/mod/github.com/go-kratos/kratos/v2@v2.7.0/log/helper.go:111
github.com/chainloop-dev/chainloop/app/controlplane/pkg/policies.NewRegistry
	tasks/chainloop/chainloop/app/controlplane/pkg/policies/registry.go:58
main.wireApp
	tasks/chainloop/chainloop/app/controlplane/cmd/wire_gen.go:95
main.main
	tasks/chainloop/chainloop/app/controlplane/cmd/main.go:140
runtime.main
	go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.1.darwin-arm64/src/runtime/proc.go:272
2024-10-08T11:22:08.778+0200	INFO	{"component": "biz.WorkflowRunExpirer", "msg": "periodic check enabled. interval=1m0s, expirationWindow=1h0m0s"}
2024-10-08T11:22:08.778+0200	INFO	{"msg": "closing the data resources"}
panic: listen tcp 0.0.0.0:9000: bind: address already in use

goroutine 1 [running]:
main.main()
	tasks/chainloop/chainloop/app/controlplane/cmd/main.go:161 +0x58c
exit status 2
make: *** [run] Error 1
```

**Comment by jiparis** [comment]
Fixed, try with latest `main`, @juamedgod

**Comment by juamedgod** [comment]
Thanks!
