### ISSUE TITLE
panic at attestation push

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#365]
```
chainloop attestation push --key env://CHAINLOOP_SIGNING_KEY 2>&1 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xd3d099]

goroutine 1 [running]:
github.com/chainloop-dev/chainloop/internal/attestation/renderer/chainloop.outputMaterials(0xc0001662a0, 0x1)
	/home/runner/work/chainloop/chainloop/internal/attestation/renderer/chainloop/v02.go:119 +0x2b9
github.com/chainloop-dev/chainloop/internal/attestation/renderer/chainloop.(*RendererV02).Header(0xc000116c[4](https://github.com/chainloop-dev/spring-petclinic/actions/runs/6332060606/job/17197920332#step:8:4)0)
	/home/runner/work/chainloop/chainloop/internal/attestation/renderer/chainloop/v02.go:74 +0x233
github.com/chainloop-dev/chainloop/internal/attestation/renderer.(*AttestationRenderer).statement(0xc000289f40)
	/home/runner/work/chainloop/chainloop/internal/attestation/renderer/renderer.go:11[5](https://github.com/chainloop-dev/spring-petclinic/actions/runs/6332060606/job/17197920332#step:8:5) +0x2e
github.com/chainloop-dev/chainloop/internal/attestation/renderer.(*AttestationRenderer).Render(0xc000289f40)
	/home/runner/work/chainloop/chainloop/internal/attestation/renderer/renderer.go:82 +0x52
github.com/chainloop-dev/chainloop/app/cli/internal/action.(*AttestationPush).Run(0xc0008bea40, 0x0?)
	/home/runner/work/chainloop/chainloop/app/cli/internal/action/attestation_push.go:115 +0x[6](https://github.com/chainloop-dev/spring-petclinic/actions/runs/6332060606/job/17197920332#step:8:6)85
github.com/chainloop-dev/chainloop/app/cli/cmd.newAttestationPushCmd.func2(0xc000[7](https://github.com/chainloop-dev/spring-petclinic/actions/runs/6332060606/job/17197920332#step:8:7)90f00?, {0x219cadd?, 0x4?, 0x219c9f5?})
	/home/runner/work/chainloop/chainloop/app/cli/cmd/attestation_push.go:73 +0x13b
github.com/spf13/cobra.(*Command).execute(0xc000790f00, {0xc00040ca00, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x[8](https://github.com/chainloop-dev/spring-petclinic/actions/runs/6332060606/job/17197920332#step:8:8)7c
github.com/spf[13](https://github.com/chainloop-dev/spring-petclinic/actions/runs/6332060606/job/17197920332#step:8:13)/cobra.(*Command).ExecuteC(0xc0000acc00)
```

**Comment by danlishka** [comment]
@migmartri I tried again with the latest version 0.19.0 and it worked fine. I will let you know if that happens again.

**Comment by migmartri** [comment]
> @migmartri I tried again with the latest version 0.19.0 and it worked fine. I will let you know if that happens again.

the problem in fact was about attaching a SARIF file
