### ISSUE TITLE
injecting go-releaser output with auto-discovery makes the CLI panic

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#962]
This is if it's passed with full auto-discovery

```
Run jq -r . <<< '[{"name":"metadata.json","path":"dist/metadata.json","internal_type":30,"type":"Metadata"},{"name":"backend","path":"dist/backend_linux_amd64_v1/backend","goos":"linux","goarch":"amd64","goamd64":"v1","internal_type":4,"type":"Binary","extra":{"Binary":"backend","Ext":"","ID":"backend","Size":46235800}},{"name":"Platform Backend_0.84.3_linux_amd64.tar.gz","path":"dist/Platform Backend_0.84.3_linux_amd64.tar.gz","goos":"linux","goarch":"amd64","goamd64":"v1","internal_type":1,"type":"Archive","extra":{"Binaries":["backend"],"Checksum":"sha256:0e1f021167eeef99114feea9a6b2f6f9e1fe7837ad62cb4e90c5190d0e187278","Format":"tar.gz","ID":"default","Replaces":null,"Size":14283602,"WrappedIn":""}},{"name":"Platform Backend_0.84.3_checksums.txt","path":"dist/Platform Backend_0.84.3_checksums.txt","internal_type":12,"type":"Checksum","extra":{}},{"name":"ghcr.io/chainloop-dev/platform/backend-migrations:v0.84.3","path":"ghcr.io/chainloop-dev/platform/backend-migrations:v0.84.3","goos":"linux","go
  
panic: interface conversion: interface {} is []interface {}, not map[string]interface {}
goroutine 1 [running]:
github.com/chainloop-dev/chainloop/internal/attestation/crafter/materials.(*CSAFCrafter).Craft(0xc001a759c0, {0x33fffe8, 0x4c07300}, {0x7fff2816eb66, 0x13})
	/home/runner/work/chainloop/chainloop/internal/attestation/crafter/materials/csaf.go:105 +0x4ef
github.com/chainloop-dev/chainloop/internal/attestation/crafter/materials.Craft({0x33fffe8, 0x4c07300}, 0xc000feef60, {0x7fff2816eb66, 0x13}, 0xc000f1b230, {0x33d8b40, 0x4c078b0}, 0xc000ff8208)
	/home/runner/work/chainloop/chainloop/internal/attestation/crafter/materials/materials.go:196 +0x486
github.com/chainloop-dev/chainloop/internal/attestation/crafter.(*Crafter).addMaterial(0xc000efdbc0, {0x33fffe8, 0x4c07300}, 0xc000feef60, {0x0, 0x0}, {0x7fff2816eb66?, 0x26b5740?}, 0xc00104e630?, 0xc000ee7aa0)
	/home/runner/work/chainloop/chainloop/internal/attestation/crafter/crafter.go:542 +0x88
github.com/chainloop-dev/chainloop/internal/attestation/crafter.(*Crafter).AddMaterialContractFree(0xc000efdbc0, {0x33fffe8, 0x4c07300}, {0x0, 0x0}, {0xc000a1a4fc, 0x8}, {0x7fff2816eb66, 0x13}, 0xc000f1b230, ...)
	/home/runner/work/chainloop/chainloop/internal/attestation/crafter/crafter.go:486 +0x24f
github.com/chainloop-dev/chainloop/internal/attestation/crafter.(*Crafter).AddMaterialContactFreeAutomatic(0xc000efdbc0, {0x33fffe8, 0x4c07300}, {0x0, 0x0}, {0x7fff2816eb66, 0x13}, 0xc000f1b230, 0xc000ee7aa0)
	/home/runner/work/chainloop/chainloop/internal/attestation/crafter/crafter.go:521 +0x157
github.com/chainloop-dev/chainloop/app/cli/internal/action.(*AttestationAdd).Run(0xc000ee7a70, {0x33fffe8, 0x4c07300}, {0x0, 0x0}, {0x0, 0x0}, {0x7fff2816eb66, 0x13}, {0x0, ...}, ...)
	/home/runner/work/chainloop/chainloop/app/cli/internal/action/attestation_add.go:[12](https://github.com/chainloop-dev/platform/actions/runs/9530947215/job/26271396478#step:7:12)3 +0x577
github.com/chainloop-dev/chainloop/app/cli/cmd.newAttestationAddCmd.func2(0xc00159af08, {0xc001580a80?, 0x4?, 0x2b5784d?})
	/home/runner/work/chainloop/chainloop/app/cli/cmd/attestation_add.go:87 +0x237
github.com/spf[13](https://github.com/chainloop-dev/platform/actions/runs/9530947215/job/26271396478#step:7:14)/cobra.(*Command).execute(0xc00159af08, {0xc001580a60, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc000fc1808)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:11[15](https://github.com/chainloop-dev/platform/actions/runs/9530947215/job/26271396478#step:7:16) +0x3ff
github.com/spf13/cobra.(*Command).Execute(0x33e3528?)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x13
main.main()
	/home/runner/work/chainloop/chainloop/app/cli/main.go:39 +0x1bd
Error: Process completed with exit code 2.
```

**Comment by migmartri** [comment]
cc/ @javirln
